workflows:
    ios-swiftly:
      name: ios_swiftly
      instance_type: mac_pro
      environment:
        vars:
          XCODE_PROJECT: "swiftly.xcodeproj"
          XCODE_SCHEME: "swiftly"
          BUNDLE_ID: "io.codemagic.swiftly"
        groups:
          - wand
          - magic
        xcode: latest
        cocoapods: default
      triggering:
        events:
          - pull_request
        branch_patterns:
          - pattern: master
            include: true
            source: false
      scripts:
        - name: Magic Number
          script: |
            echo "MAGIC_NUMBER ${MAGIC_NUMBER}"
        
