workflows:
    ios-swiftly:
      name: ios_swiftly
      instance_type: mac_pro
      environment:
        ios_signing:
          distribution_type: app_store # ad_hoc | development | enterprise
          bundle_identifier: io.codemagic.cmswiftly
        groups:
          - ios_credentials
        vars:
          XCODE_WORKSPACE: "swiftly.xcworkspace"
          XCODE_SCHEME: "swiftly"
          APP_STORE_APP_ID: 1570610860
        xcode: 13.3
        cocoapods: default
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: other
            include: true
            source: true
      scripts:
        - name: Increment version and build iOS app 
          script: |
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
            xcode-project use-profiles && xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        app_store_connect:
          api_key: $APP_STORE_CONNECT_PRIVATE_KEY
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER   
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID         
        email:
            recipients:
            - kevin@nevercode.io
