sed -i.bak "s/\$BUILD_DATE/$BUILD_DATE/" .templates/jira.json
sed -i.bak "s/\$ARTIFACT_NAME/$ARTIFACT_NAME/" .templates/jira.json
sed -i.bak "s/\$ARTIFACT_URL/$TEST_URL/" .templates/jira.json
sed -i.bak "s/\$FCI_COMMIT/$COMMIT/" .templates/jira.json
sed -i.bak "s/\$GIT_COMMIT_MESSAGE/$GIT_COMMIT_MESSAGE/" .templates/jira.json
sed -i.bak "s/\$VERSION_NAME/$VERSION_NAME/" .templates/jira.json
sed -i.bak "s/\$BUILD_VERSION/$BUILD_VERSION/" .templates/jira.json
sed -i.bak "s/\$BUNDLE/$BUNDLE/" .templates/jira.json
sed -i.bak "s/\$TYPE/$TYPE/" .templates/jira.json